config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resources :posts
  end

  #resources :sessions, only: [:create, :new, :destoy]
    get '/logout', to: 'sessions#destroy'
    get '/login', to: 'sessions#new'
    post '/login' => 'sessions#create'
    #this is how to write out your own url
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user 
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id] 
  end 
  
  helper_method :current_user
  
  def authenticate_user! 
    redirect_to '/login' unless current_user 
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = User.find(params[:user_id])
    @posts = Post.where(user_id: @user.id)
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    if @user == current_user
      @post = Post.new
    else
      redirect_to user_posts_path(@user)
  end

  def create
    @user = User.find(params[:user_id])
    @post = Post.new(post_params)
    if @post.save
      redirect_to user_post_path(@user, @post)
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to user_post_path(@user, @post)
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
    @post.destroy
    redirect_to user_posts_path(@user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:name])
   
     if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_posts_path(user)
     else
      redirect_to '/login'
     end
   end
    
  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:new, :create]
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.name.downcase!
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :bio, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#=link href="https://fonts.googleapis.com/css?family=Ultra&display=swap" rel="stylesheet" %>
  </head>

  <body>
  <header>
    <% if current_user %>
      <a href= '/logout'>Log Out</a>
    <% else %>
      <a href= '/login'>Log In</a>
      <a href= '/users/new'>Create Account</a>
    <% end %>
  </header>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h2>Edit <%= @post.title %></h2>
<%= form_for [@user, @post] do |f| %>
  <%= f.text_field :title, placeholder: "Title" %>
  <%= f.text_area :body, placeholder: "Body" %>
  <%= f.text_field :user_id, value: @user.id %>
  <%= f.submit "Submit"%>
<% end %>

<%= link_to @post.title, user_post_path(@user, @post) %>

app/views/posts/index.html.erb
<h2><%= @user.name %>'s Posts</h2>
<% @posts.each do |post| %>
  <p><%= link_to post.title, user_post_path(@user,post) %></p>
<% end %>
<hr>
<% if @user == current_user %>
  <%= link_to "Create New Post", new_user_post_path(@user) %>
<% end %>

app/views/posts/new.html.erb
<h2>Create New Post</h2>
<%= form_for [@user, @post] do |f| %>
  <%= f.text_field :title, placeholder: "Title" %>
  <%= f.text_area :body, placeholder: "Body" %>
  <%= f.text_field :user_id, value: @user.id %>
  <%= f.submit "Submit"%>
<% end %>

<p><%= link_to "Post List", user_posts_path(@user) %></p>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<hr>

<%= link_to "Post List", user_posts_path(@user) %>
<%= link_to "Edit Post", edit_user_post_path(@user, @post) %>
<%= form_for [@user, @post], html: {method: "delete"} do |f| %>
  <%= f.submit "Delete Post" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.text_field :name, placeholder: "Name" %>
  <%= f.text_area :bio, placeholder: "Bio" %>
  <%= f.password_field :password, placeholder: "Password" %>
  <%= f.submit "Submit"%>
<% end %>

app/views/users/edit.html.erb
<h2>Edit <%= @user.name %></h2>
<%= render partial: 'form' %>
<hr>
<p><%= link_to @user.name, @user %></p>

app/views/users/index.html.erb
<h2>List of Users</h2>
<% @users.each do |user| %>
  <p><%= link_to user.name, user %></p>
<% end %>

<hr>
<p><%= link_to "Create New User", new_user_path %></p>

app/views/users/new.html.erb
<h2>Create New User</h2>
<%= render partial: 'form' %>
<hr>
<p><%= link_to "Users List", users_path %>

app/views/users/show.html.erb
<h2><%= @user.name %></h2>
<p><%= @user.bio %></p>
<%= link_to 'text', user_posts_path(@user) %>
<hr>
<p><%= link_to "Users List", users_path %></p>
<p><%= link_to "Edit", edit_user_path %></p>
<%= form_for @user, html: {method: "delete"} do |f| %>
  <%= f.submit "Delete #{@user.name}" %>
<% end %>
<%= link_to 'go to user profile', @user %>
<%= link_to 'create new post', new_user_post_path(@user) %>